version: '3.8'

services:
  nodejs-app:
    container_name: nodejs-app
    build:
      context: ./node-app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mysql-db
    environment:
      - DATABASE_HOST=mysql-db
      - DATABASE_USER=myuser
      - DATABASE_PASSWORD=mypassword
      - DATABASE_NAME=mydatabase
    volumes:
      - ./node-app:/usr/src/app  # Mount local directory into the container
      - /usr/src/app/node_modules  # Prevent overriding node_modules in the container

  mysql-db:
    container_name: mysql-db
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
